SHOW DATABASES;
CREATE DATABASE pizza_sales_analysis;
USE pizza_sales_analysis;
CREATE TABLE ORDER_1(ID INT , ORDER_DATE DATE);
ALTER TABLE ORDER_1 ADD COLUMN ORDER_TIME TIME AFTER ORDER_DATE;
ALTER TABLE ORDER_1 RENAME ORDERS;
ALTER TABLE ORDERS MODIFY ID INT PRIMARY KEY;
select*FROM ORDERS;
DESC ORDERS;
